/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "logout": [],
    "dashboard": [],
    "module.select": [],
    "module.select.store": [],
    "account.edit": [],
    "account.profile.update": [],
    "account.password.update": [],
    "register.choice": [],
    "register.success": [],
    "attendance.dashboard.admin": [],
    "attendance.dashboard.staff": [],
    "attendance.scan": [],
    "attendance.process": [],
    "attendance.section": [],
    "attendance.feedback.store": [],
    "attendance.register.student.form": [],
    "attendance.register.employee.form": [],
    "attendance.register.student.store": [],
    "attendance.register.employee.store": [],
    "attendance.pending.index": [],
    "attendance.pending.students.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.pending.students.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.pending.employees.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.pending.employees.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.students.index": [],
    "attendance.employees.index": [],
    "attendance.changeVideo": [],
    "attendance.uploadVideo": [],
    "attendance.feedback.settings": [],
    "attendance.feedback.settings.update": [],
    "attendance.section.settings": [],
    "attendance.section.settings.update": [],
    "attendance.sms.page": [],
    "attendance.sms.send": [],
    "attendance.sms.scanMessage": [],
    "attendance.sms.scanMessage.update": [],
    "attendance.sms.count": [],
    "attendance.students.create": [],
    "attendance.students.store": [],
    "attendance.students.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.students.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.students.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.employees.create": [],
    "attendance.employees.store": [],
    "attendance.employees.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.employees.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.employees.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.feedback.index": [],
    "attendance.logs.index": [],
    "attendance.logs.reports.hub": [],
    "attendance.logs.reports.dashboard": [],
    "attendance.logs.reports.export": [],
    "attendance.logs.export.excel": [],
    "attendance.logs.export.pdf": [],
    "library.dashboard.admin": [],
    "library.dashboard.staff": [],
    "library.register.student.form": [],
    "library.register.employee.form": [],
    "library.register.student.store": [],
    "library.register.employee.store": [],
    "library.filters.years": [],
    "library.filters.courses": [],
    "library.books.copies": [],
    "library.feedback.create": [],
    "library.feedback.store": [],
    "library.student.qr.profile": [
        {
            "name": "qrcode",
            "required": true
        }
    ],
    "library.students.profile.request": [],
    "library.kiosk.scan": [],
    "library.checkout.process": [],
    "library.checkout.bulk": [],
    "library.landing": [],
    "library.opac.book.details": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "library.opac.reserve": [],
    "library.rooms.book": [],
    "library.room-reservations.store": [],
    "library.rooms.schedule": [],
    "library.rooms.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.admin.activities.index": [],
    "library.admin.activities.recent": [],
    "library.admin.activities.mark_seen": [],
    "library.books.coursesForPrograms": [],
    "library.book.create": [],
    "library.book.store": [],
    "library.book.show": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "library.book.edit": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "library.book.update": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "library.book.destroy": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "library.books.index": [],
    "library.books.copies.staff": [],
    "library.books.archived": [],
    "library.books.trash": [],
    "library.books.archive": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "library.books.unarchive": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "library.books.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.books.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.books.import": [],
    "library.ebooks.index": [],
    "library.ebooks.create": [],
    "library.ebooks.store": [],
    "library.ebooks.show": [
        {
            "name": "ebook",
            "required": true,
            "binding": "id"
        }
    ],
    "library.ebooks.edit": [
        {
            "name": "ebook",
            "required": true
        }
    ],
    "library.ebooks.update": [
        {
            "name": "ebook",
            "required": true
        }
    ],
    "library.ebooks.destroy": [
        {
            "name": "ebook",
            "required": true,
            "binding": "id"
        }
    ],
    "library.ebooks.courses": [
        {
            "name": "programId",
            "required": true
        }
    ],
    "library.export.books": [],
    "library.transactions.export": [],
    "library.book.report.download": [],
    "library.reports.library_holdings.create": [],
    "library.reports.library_holdings.download": [],
    "library.rfid.scanner": [],
    "library.rfid.scan": [],
    "library.patron.suggestions": [],
    "library.book.suggestions": [],
    "library.book.title.log.suggestions": [],
    "library.catalog.copy.openlibrary.form": [],
    "library.catalog.copy.openlibrary.search": [],
    "library.catalog.copy.openlibrary.store": [],
    "library.feedback.index": [],
    "library.feedback.export.csv": [],
    "library.holidays.list": [],
    "library.holidays.toggle": [],
    "library.holidays.all": [],
    "library.sms.send": [],
    "library.logs.index": [],
    "library.logs.store": [],
    "library.logs.renew": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "library.prospectus.index": [],
    "library.prospectus.storeProgram": [],
    "library.prospectus.getProgramYears": [
        {
            "name": "program",
            "required": true,
            "binding": "id"
        }
    ],
    "library.prospectus.storeCourse": [
        {
            "name": "program",
            "required": true,
            "binding": "id"
        }
    ],
    "library.prospectus.updateCourse": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "library.prospectus.destroyCourse": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "library.prospectus.updateProgram": [
        {
            "name": "program",
            "required": true,
            "binding": "id"
        }
    ],
    "library.prospectus.destroyProgram": [
        {
            "name": "program",
            "required": true,
            "binding": "id"
        }
    ],
    "library.students.report": [],
    "library.students.import": [],
    "library.students.export": [],
    "library.students.index": [],
    "library.students.create": [],
    "library.students.store": [],
    "library.students.show": [
        {
            "name": "student",
            "required": true
        }
    ],
    "library.students.edit": [
        {
            "name": "student",
            "required": true
        }
    ],
    "library.students.update": [
        {
            "name": "student",
            "required": true
        }
    ],
    "library.students.destroy": [
        {
            "name": "student",
            "required": true
        }
    ],
    "library.idcard.download": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.students.pending.requests": [],
    "library.admin.requests.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.admin.requests.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.idcard.generate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.idcard.front": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.idcard.back": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.students.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.students.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.pending.index": [],
    "library.pending.employees": [],
    "library.employees.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.employees.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.employees.index": [],
    "library.employees.create": [],
    "library.employees.store": [],
    "library.employees.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.employees.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.employees.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.employees.id.front": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.employees.id.back": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.employees.id.download": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.rooms.pending": [],
    "library.rooms.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.rooms.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.resrooms.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.rooms.check": [],
    "library.rooms.logs": [],
    "library.rooms.index": [],
    "library.rooms.create": [],
    "library.rooms.store": [],
    "library.rooms.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.rooms.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.rooms.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.circulation.policy.edit": [],
    "library.circulation.policy.update": [],
    "library.fines.outstanding": [],
    "library.fines.logs.clear": [
        {
            "name": "bookLog",
            "required": true,
            "binding": "id"
        }
    ],
    "library.sms.page": [],
    "library.sms.scan-message": [],
    "library.sms.scan-message.update": [],
    "library.sms.send-one-student": [],
    "library.sms.send-overdue": [],
    "library.sms.count": [],
    "library.admin.catalog_frameworks.index": [],
    "library.admin.catalog_frameworks.edit": [
        {
            "name": "catalog_framework",
            "required": true,
            "binding": "id"
        }
    ],
    "library.admin.catalog_frameworks.fields.update": [
        {
            "name": "catalog_framework",
            "required": true,
            "binding": "id"
        }
    ],
    "library.admin.catalog_frameworks.fields.attach": [
        {
            "name": "catalog_framework",
            "required": true,
            "binding": "id"
        }
    ],
    "library.admin.catalog_frameworks.marc_fields.store": [
        {
            "name": "catalog_framework",
            "required": true,
            "binding": "id"
        }
    ],
    "library.admin.catalog_frameworks.fields.detach": [
        {
            "name": "catalog_framework",
            "required": true,
            "binding": "id"
        },
        {
            "name": "field",
            "required": true,
            "binding": "id"
        }
    ],
    "library.admin.catalog_select_options.index": [],
    "library.admin.catalog_select_options.store": [],
    "library.admin.catalog_select_options.destroy": [],
    "library.files.index": [],
    "library.files.upload": [],
    "library.files.view": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.files.download": [
        {
            "name": "id",
            "required": true
        }
    ],
    "library.files.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "super-admin.dashboard": [],
    "staff-users.index": [],
    "staff-users.create": [],
    "staff-users.store": [],
    "staff-users.edit": [
        {
            "name": "staffUser",
            "required": true,
            "binding": "id"
        }
    ],
    "staff-users.update": [
        {
            "name": "staffUser",
            "required": true,
            "binding": "id"
        }
    ],
    "staff-users.status.update": [
        {
            "name": "staffUser",
            "required": true,
            "binding": "id"
        }
    ],
    "staff-users.destroy": [
        {
            "name": "staffUser",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
