import {
    Archive,
    ArrowLeftRight,
    BookMarked,
    BookOpen,
    BookPlus,
    Braces,
    Building2,
    CalendarDays,
    CircleDollarSign,
    ClipboardList,
    DoorOpen,
    FileBarChart,
    FileDown,
    FolderOpen,
    Footprints,
    Globe,
    GraduationCap,
    History,
    Hourglass,
    LayoutDashboard,
    Library,
    ListTree,
    MessagesSquare,
    ScanBarcode,
    ScanLine,
    Send,
    Shield,
    SlidersHorizontal,
    Trash2,
    UserCog,
    Users,
    Video,
} from 'lucide-react';

import { dashboardRouteFor } from '@/config/modules';
import type { PageProps } from '@/types';
import type { NavigationGroup } from '@/types/navigation';

const adminRoles = ['library_admin'];

export function libraryNavigation(auth: PageProps['auth']): NavigationGroup[] {
    return [
        {
            id: 'workspace',
            label: 'Workspace',
            items: [
                {
                    id: 'dashboard',
                    label: 'Dashboard',
                    icon: LayoutDashboard,
                    routeName: dashboardRouteFor('library', auth),
                    keywords: ['overview', 'home', 'command center'],
                },
                {
                    id: 'circulation-desk',
                    label: 'Circulation desk',
                    icon: ArrowLeftRight,
                    routeName: 'library.logs.index',
                    routePrefixes: ['library.logs.'],
                    keywords: ['checkout', 'check in', 'return', 'renew', 'loans'],
                    roles: adminRoles,
                },
                {
                    id: 'pending-registrations',
                    label: 'Pending registrations',
                    icon: Hourglass,
                    routeName: 'library.pending.index',
                    routePrefixes: ['library.pending.'],
                    keywords: ['approvals', 'students', 'employees', 'patrons'],
                    badgeKey: 'pendingPatrons',
                    badgeTone: 'warning',
                    roles: adminRoles,
                },
                {
                    id: 'room-requests',
                    label: 'Room requests',
                    icon: DoorOpen,
                    routeName: 'library.rooms.pending',
                    keywords: ['pending reservations', 'approve rooms'],
                    badgeKey: 'pendingRooms',
                    badgeTone: 'warning',
                    roles: adminRoles,
                },
                {
                    id: 'outstanding-fines',
                    label: 'Outstanding fines',
                    icon: CircleDollarSign,
                    routeName: 'library.fines.outstanding',
                    routePrefixes: ['library.fines.'],
                    keywords: ['overdue', 'clearance', 'payments'],
                    badgeKey: 'outstandingFines',
                    badgeTone: 'danger',
                    roles: adminRoles,
                },
            ],
        },
        {
            id: 'manage',
            label: 'Manage',
            items: [
                {
                    id: 'catalog-collections',
                    label: 'Catalog & collections',
                    icon: Library,
                    keywords: ['books', 'ebooks', 'copies'],
                    children: [
                        {
                            id: 'books',
                            label: 'Books',
                            icon: BookOpen,
                            routeName: 'library.books.index',
                            routePrefixes: ['library.book.', 'library.books.'],
                            routeExclusions: ['library.books.archived', 'library.books.trash'],
                            keywords: ['catalog', 'copies', 'holdings'],
                        },
                        {
                            id: 'ebooks',
                            label: 'E-books',
                            icon: BookMarked,
                            routeName: 'library.ebooks.index',
                            routePrefixes: ['library.ebooks.'],
                            keywords: ['digital collection'],
                        },
                        {
                            id: 'copy-cataloging',
                            label: 'Copy cataloging',
                            icon: BookPlus,
                            routeName: 'library.catalog.copy.openlibrary.form',
                            routePrefixes: ['library.catalog.copy.openlibrary.'],
                            keywords: ['isbn', 'open library', 'add book'],
                        },
                        {
                            id: 'rfid-scanner',
                            label: 'RFID copy scanner',
                            icon: ScanBarcode,
                            routeName: 'library.rfid.scanner',
                            keywords: ['barcode', 'accession', 'copy status'],
                        },
                        {
                            id: 'archived-books',
                            label: 'Archived books',
                            icon: Archive,
                            routeName: 'library.books.archived',
                            keywords: ['inactive catalog records'],
                        },
                        {
                            id: 'trash',
                            label: 'Trash',
                            icon: Trash2,
                            routeName: 'library.books.trash',
                            keywords: ['deleted books', 'restore'],
                        },
                    ],
                },
                {
                    id: 'patrons',
                    label: 'Patrons',
                    icon: Users,
                    roles: adminRoles,
                    children: [
                        {
                            id: 'students',
                            label: 'Students',
                            icon: GraduationCap,
                            routeName: 'library.students.index',
                            routePrefixes: ['library.students.'],
                            routeExclusions: ['library.students.pending.requests'],
                            keywords: ['student data', 'id cards'],
                            roles: adminRoles,
                        },
                        {
                            id: 'employees',
                            label: 'Employees',
                            icon: UserCog,
                            routeName: 'library.employees.index',
                            routePrefixes: ['library.employees.'],
                            keywords: ['faculty', 'staff data', 'id cards'],
                            roles: adminRoles,
                        },
                        {
                            id: 'profile-requests',
                            label: 'Profile requests',
                            icon: ClipboardList,
                            routeName: 'library.students.pending.requests',
                            keywords: ['edit requests', 'patron changes'],
                            roles: adminRoles,
                        },
                    ],
                },
                {
                    id: 'rooms',
                    label: 'Rooms',
                    icon: Building2,
                    roles: adminRoles,
                    children: [
                        {
                            id: 'manage-rooms',
                            label: 'Manage rooms',
                            icon: DoorOpen,
                            routeName: 'library.rooms.index',
                            routePrefixes: ['library.rooms.create', 'library.rooms.edit'],
                            roles: adminRoles,
                        },
                        {
                            id: 'reservation-history',
                            label: 'Reservation history',
                            icon: History,
                            routeName: 'library.rooms.logs',
                            keywords: ['room logs'],
                            roles: adminRoles,
                        },
                    ],
                },
                {
                    id: 'library-visits',
                    label: 'Library visits',
                    icon: Footprints,
                    roles: adminRoles,
                    children: [
                        {
                            id: 'visit-logs',
                            label: 'Visit logs',
                            icon: ClipboardList,
                            routeName: 'library.attendance.logs',
                            roles: adminRoles,
                        },
                        {
                            id: 'visit-reports',
                            label: 'Visit reports',
                            icon: FileBarChart,
                            routeName: 'library.attendance.logs.reports.hub',
                            routePrefixes: ['library.attendance.logs.reports.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'visit-feedback-settings',
                            label: 'Feedback settings',
                            icon: SlidersHorizontal,
                            routeName: 'library.attendance.feedback.settings',
                            routePrefixes: ['library.attendance.feedback.settings'],
                            roles: adminRoles,
                        },
                        {
                            id: 'visit-feedback-responses',
                            label: 'Feedback responses',
                            icon: MessagesSquare,
                            routeName: 'library.attendance.feedbacks',
                            roles: adminRoles,
                        },
                        {
                            id: 'scanner-video',
                            label: 'Scanner video',
                            icon: Video,
                            routeName: 'library.attendance.video',
                            routePrefixes: ['library.attendance.uploadVideo'],
                            roles: adminRoles,
                        },
                    ],
                },
            ],
        },
        {
            id: 'insights',
            label: 'Insights',
            items: [
                {
                    id: 'reports-feedback',
                    label: 'Reports & feedback',
                    icon: FileBarChart,
                    children: [
                        {
                            id: 'holdings-report',
                            label: 'Holdings report',
                            icon: FileBarChart,
                            routeName: 'library.reports.library_holdings.create',
                            routePrefixes: ['library.reports.library_holdings.'],
                            keywords: ['collection statistics'],
                        },
                        {
                            id: 'book-report-pdf',
                            label: 'Book report PDF',
                            icon: FileDown,
                            routeName: 'library.book.report.download',
                            navigationMode: 'document',
                            keywords: ['download', 'export'],
                        },
                        {
                            id: 'student-feedback',
                            label: 'Student feedback',
                            icon: MessagesSquare,
                            routeName: 'library.feedback.index',
                            routePrefixes: ['library.feedback.'],
                        },
                    ],
                },
            ],
        },
        {
            id: 'administration',
            label: 'Administration',
            items: [
                {
                    id: 'administration-tools',
                    label: 'Settings & administration',
                    icon: Shield,
                    roles: adminRoles,
                    children: [
                        {
                            id: 'circulation-policy',
                            label: 'Circulation policy',
                            icon: SlidersHorizontal,
                            routeName: 'library.circulation.policy.edit',
                            routePrefixes: ['library.circulation.policy.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'marc-frameworks',
                            label: 'MARC frameworks',
                            icon: Braces,
                            routeName: 'library.admin.catalog_frameworks.index',
                            routePrefixes: ['library.admin.catalog_frameworks.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'catalog-options',
                            label: 'Catalog options',
                            icon: ListTree,
                            routeName: 'library.admin.catalog_select_options.index',
                            routePrefixes: ['library.admin.catalog_select_options.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'prospectus',
                            label: 'Prospectus',
                            icon: BookMarked,
                            routeName: 'library.prospectus.index',
                            routePrefixes: ['library.prospectus.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'staff-accounts',
                            label: 'Staff accounts',
                            icon: UserCog,
                            routeName: 'staff-users.index',
                            routePrefixes: ['staff-users.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'sms',
                            label: 'SMS',
                            icon: Send,
                            routeName: 'library.sms.page',
                            routePrefixes: ['library.sms.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'repository',
                            label: 'Repository',
                            icon: FolderOpen,
                            routeName: 'library.files.index',
                            routePrefixes: ['library.files.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'audit-log',
                            label: 'Audit log',
                            icon: History,
                            routeName: 'library.admin.activities.index',
                            routePrefixes: ['library.admin.activities.'],
                            roles: adminRoles,
                        },
                    ],
                },
            ],
        },
        {
            id: 'public-tools',
            label: 'Public tools',
            items: [
                {
                    id: 'public-tools-menu',
                    label: 'Open public tools',
                    icon: Globe,
                    children: [
                        {
                            id: 'opac',
                            label: 'OPAC',
                            icon: BookOpen,
                            routeName: 'library.landing',
                            navigationMode: 'new-tab',
                            keywords: ['public catalog'],
                        },
                        {
                            id: 'patron-kiosk',
                            label: 'Patron kiosk',
                            icon: ScanLine,
                            routeName: 'library.kiosk.scan',
                            navigationMode: 'new-tab',
                            keywords: ['lookup', 'qr'],
                        },
                        {
                            id: 'visit-scanner',
                            label: 'Library-visit scanner',
                            icon: Footprints,
                            routeName: 'library.attendance.scanner',
                            navigationMode: 'new-tab',
                            roles: adminRoles,
                        },
                        {
                            id: 'book-room',
                            label: 'Book a room',
                            icon: CalendarDays,
                            routeName: 'library.rooms.book',
                            navigationMode: 'new-tab',
                        },
                        {
                            id: 'room-schedule',
                            label: 'Room schedule',
                            icon: DoorOpen,
                            routeName: 'library.rooms.schedule',
                            navigationMode: 'new-tab',
                        },
                    ],
                },
            ],
        },
    ];
}
