import {
    BookMarked,
    BookOpen,
    Braces,
    CalendarCheck,
    Database,
    DoorOpen,
    FileBarChart,
    FileDown,
    FolderOpen,
    History,
    Home,
    Library,
    ListTree,
    MessagesSquare,
    ScanLine,
    Send,
    Shield,
    UserCog,
    Video,
} from 'lucide-react';

import type { PageProps } from '@/types';
import type { NavigationGroup } from '@/types/navigation';

const adminRoles = ['library_admin'];

export function libraryNavigation(_auth: PageProps['auth']): NavigationGroup[] {
    return [
        {
            id: 'menu',
            label: 'Menu',
            items: [
                {
                    id: 'home',
                    label: 'Home',
                    icon: Home,
                    routeName: 'library.books.index',
                    routePrefixes: ['library.book.', 'library.books.'],
                },
                {
                    id: 'library-kiosk',
                    label: 'Library Kiosk',
                    icon: ScanLine,
                    routeName: 'library.kiosk.scan',
                    external: true,
                },
                {
                    id: 'attendance',
                    label: 'Attendance',
                    icon: CalendarCheck,
                    roles: adminRoles,
                    children: [
                        {
                            id: 'attendance-scanner',
                            label: 'Attendance',
                            icon: CalendarCheck,
                            routeName: 'library.attendance.scanner',
                            external: true,
                            roles: adminRoles,
                        },
                        {
                            id: 'attendance-logout-feedback',
                            label: 'Logout Feedback Settings',
                            icon: MessagesSquare,
                            routeName: 'library.attendance.feedback.settings',
                            routePrefixes: ['library.attendance.feedback.settings'],
                            roles: adminRoles,
                        },
                        {
                            id: 'attendance-feedback-responses',
                            label: 'View Feedback Responses',
                            icon: MessagesSquare,
                            routeName: 'library.attendance.feedbacks',
                            roles: adminRoles,
                        },
                        {
                            id: 'change-attendance-video',
                            label: 'Change Scanner Video',
                            icon: Video,
                            routeName: 'library.attendance.video',
                            routePrefixes: ['library.attendance.uploadVideo'],
                            roles: adminRoles,
                        },
                    ],
                },
                {
                    id: 'data',
                    label: 'Data',
                    icon: Database,
                    children: [
                        {
                            id: 'student-data',
                            label: 'Student Data',
                            icon: Database,
                            routeName: 'library.students.index',
                            routePrefixes: ['library.students.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'faculty-staff-data',
                            label: 'Faculty & Staff Data',
                            icon: Database,
                            routeName: 'library.employees.index',
                            routePrefixes: ['library.employees.'],
                            roles: adminRoles,
                        },
                    ],
                },
                {
                    id: 'opac',
                    label: 'OPAC',
                    icon: BookOpen,
                    routeName: 'library.landing',
                    external: true,
                },
                {
                    id: 'circulation',
                    label: 'Circulation',
                    icon: Library,
                    children: [
                        {
                            id: 'circulation-desk',
                            label: 'Circulation',
                            icon: Library,
                            routeName: 'library.logs.index',
                            routePrefixes: ['library.logs.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'copy-cataloging',
                            label: 'Copy Cataloging',
                            icon: Library,
                            routeName: 'library.catalog.copy.openlibrary.form',
                            routePrefixes: ['library.catalog.copy.openlibrary.'],
                        },
                        {
                            id: 'circulation-policy',
                            label: 'Circulation Policy',
                            icon: Library,
                            routeName: 'library.circulation.policy.edit',
                            routePrefixes: ['library.circulation.policy.'],
                            roles: adminRoles,
                        },
                    ],
                },
                {
                    id: 'reports',
                    label: 'Reports',
                    icon: FileBarChart,
                    children: [
                        {
                            id: 'outstanding-fines',
                            label: 'Outstanding Fines',
                            icon: FileBarChart,
                            routeName: 'library.fines.outstanding',
                            routePrefixes: ['library.fines.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'holdings-report',
                            label: 'Library Holdings Report',
                            icon: FileBarChart,
                            routeName: 'library.reports.library_holdings.create',
                            routePrefixes: ['library.reports.library_holdings.'],
                        },
                        {
                            id: 'attendance-logs',
                            label: 'Attendance Logs',
                            icon: CalendarCheck,
                            routeName: 'library.attendance.logs',
                            routePrefixes: ['library.attendance.logs'],
                            roles: adminRoles,
                        },
                        {
                            id: 'book-report-pdf',
                            label: 'Download Book Report (PDF)',
                            icon: FileDown,
                            routeName: 'library.book.report.download',
                            external: true,
                        },
                        {
                            id: 'student-feedback',
                            label: 'Student Feedback',
                            icon: MessagesSquare,
                            routeName: 'library.feedback.index',
                            routePrefixes: ['library.feedback.'],
                        },
                        {
                            id: 'activity-log',
                            label: 'Activity log',
                            icon: FileBarChart,
                            routeName: 'library.admin.activities.index',
                            routePrefixes: ['library.admin.activities.'],
                        },
                        {
                            id: 'reservation-logs',
                            label: 'Reservation Logs',
                            icon: History,
                            routeName: 'library.rooms.logs',
                            roles: adminRoles,
                        },
                    ],
                },
                {
                    id: 'admin',
                    label: 'Admin',
                    icon: Shield,
                    roles: adminRoles,
                    children: [
                        {
                            id: 'repository',
                            label: 'Repository',
                            icon: FolderOpen,
                            routeName: 'library.files.index',
                            routePrefixes: ['library.files.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'prospectus',
                            label: 'Prospectus Manager',
                            icon: BookMarked,
                            routeName: 'library.prospectus.index',
                            routePrefixes: ['library.prospectus.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'view-users',
                            label: 'View Pantas Users',
                            icon: UserCog,
                            routeName: 'staff-users.index',
                            routePrefixes: ['staff-users.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'marc-frameworks',
                            label: 'MARC catalog frameworks',
                            icon: Braces,
                            routeName: 'library.admin.catalog_frameworks.index',
                            routePrefixes: ['library.admin.catalog_frameworks.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'catalog-options',
                            label: 'Catalog dropdown options',
                            icon: ListTree,
                            routeName: 'library.admin.catalog_select_options.index',
                            routePrefixes: ['library.admin.catalog_select_options.'],
                            roles: adminRoles,
                        },
                        {
                            id: 'sms-blast',
                            label: 'SMS Blast',
                            icon: Send,
                            routeName: 'library.sms.page',
                            routePrefixes: ['library.sms.'],
                            roles: adminRoles,
                        },
                    ],
                },
                {
                    id: 'room-reservations',
                    label: 'Room Reservations',
                    icon: DoorOpen,
                    children: [
                        {
                            id: 'manage-rooms',
                            label: 'Manage Rooms',
                            icon: DoorOpen,
                            routeName: 'library.rooms.index',
                            routePrefixes: ['library.rooms.create', 'library.rooms.edit'],
                            roles: adminRoles,
                        },
                        {
                            id: 'book-room',
                            label: 'Book a Room',
                            icon: DoorOpen,
                            routeName: 'library.rooms.book',
                            external: true,
                        },
                        {
                            id: 'view-schedule',
                            label: 'View Schedule',
                            icon: DoorOpen,
                            routeName: 'library.rooms.schedule',
                            external: true,
                        },
                        {
                            id: 'pending-reservations',
                            label: 'Pending Reservations',
                            icon: DoorOpen,
                            routeName: 'library.rooms.pending',
                            roles: adminRoles,
                        },
                    ],
                },
            ],
        },
    ];
}
